// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlTask = "eml_tasks"

// EmlTask mapped from table <eml_tasks>
type EmlTask struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid         int64      `gorm:"column:cid;type:bigint;not null;comment:商户ID，关联商户" json:"cid"`                                                                                                                   // 商户ID，关联商户
	FromEmail   string     `gorm:"column:from_email;type:varchar(255);not null;comment:发信人地址" json:"from_email"`                                                                                                   // 发信人地址
	UserTag     string     `gorm:"column:user_tag;type:varchar(64);not null;comment:用于筛选用户" json:"user_tag"`                                                                                                       // 用于筛选用户
	TemplateID  int64      `gorm:"column:template_id;type:bigint;not null;comment:模板ID" json:"template_id"`                                                                                                        // 模板ID
	Status      string     `gorm:"column:status;type:varchar(32);not null;index:email_tasks_status_fetch_time_index,priority:1;default:pending;comment:发件任务状态（pending、processing、finished、invalid）" json:"status"` // 发件任务状态（pending、processing、finished、invalid）
	Type        string     `gorm:"column:type;type:varchar(36);not null;default:market;comment:发件任务类型" json:"type"`                                                                                                // 发件任务类型
	ProcessInfo string     `gorm:"column:process_info;type:varchar(8192);not null;comment:发件任务处理信息" json:"process_info"`                                                                                           // 发件任务处理信息
	Version     int32      `gorm:"column:version;type:int;not null;comment:乐观锁" json:"version"`                                                                                                                    // 乐观锁
	FetchTime   *time.Time `gorm:"column:fetch_time;type:timestamp;index:email_tasks_status_fetch_time_index,priority:2;comment:上次获取时间" json:"fetch_time"`                                                         // 上次获取时间
	TotalNum    int32      `gorm:"column:total_num;type:int;not null;comment:发件总数 等价于 收件人数量" json:"total_num"`                                                                                                     // 发件总数 等价于 收件人数量
	SuccessNum  int32      `gorm:"column:success_num;type:int;not null;comment:成功发送的数量" json:"success_num"`                                                                                                        // 成功发送的数量
	FailNum     int32      `gorm:"column:fail_num;type:int;not null;comment:邮件任务失败的数量" json:"fail_num"`                                                                                                            // 邮件任务失败的数量
	InvalidNum  int32      `gorm:"column:invalid_num;type:int;not null;comment:收件人地址有误总数" json:"invalid_num"`                                                                                                      // 收件人地址有误总数
	PendingNum  int32      `gorm:"column:pending_num;type:int;not null;comment:等待被发送的邮件数量" json:"pending_num"`                                                                                                     // 等待被发送的邮件数量
	OpenNum     int32      `gorm:"column:open_num;type:int;not null;comment:收到邮件后，打开邮件的行为" json:"open_num"`                                                                                                        // 收到邮件后，打开邮件的行为
	OpenNumDe   int32      `gorm:"column:open_num_de;type:int;not null;comment:对”打开”行为基于同一封邮件做去重" json:"open_num_de"`                                                                                              // 对”打开”行为基于同一封邮件做去重
	ClickNum    int32      `gorm:"column:click_num;type:int;not null;comment:收到邮件后，打开邮件后，点击了邮件中的URL" json:"click_num"`                                                                                             // 收到邮件后，打开邮件后，点击了邮件中的URL
	ClickNumDe  int32      `gorm:"column:click_num_de;type:int;not null;comment:对”点击”行为基于同一封邮件做去重" json:"click_num_de"`                                                                                            // 对”点击”行为基于同一封邮件做去重
	UpdateTime  time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                                                                           // 更新时间
	CreateTime  time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                                                           // 创建时间
}

// TableName EmlTask's table name
func (*EmlTask) TableName() string {
	return TableNameEmlTask
}
