// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlDomainCredibility = "eml_domain_credibility"

// EmlDomainCredibility mapped from table <eml_domain_credibility>
type EmlDomainCredibility struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid             int64     `gorm:"column:cid;type:bigint;not null" json:"cid"`
	FromAddress     string    `gorm:"column:from_address;type:varchar(255);not null;comment:发件地址" json:"from_address"`                                        // 发件地址
	Domain          string    `gorm:"column:domain;type:varchar(255);not null;comment:收件域名，以@开头" json:"domain"`                                               // 收件域名，以@开头
	LastSentTime    time.Time `gorm:"column:last_sent_time;type:timestamp;not null;default:1970-01-01 00:00:01;comment:上一次向收件域发送邮件的时间" json:"last_sent_time"` // 上一次向收件域发送邮件的时间
	SuccessRateDay  *float64  `gorm:"column:success_rate_day;type:decimal(5,2);comment:每日成功率" json:"success_rate_day"`                                        // 每日成功率
	SuccessRateHour *float64  `gorm:"column:success_rate_hour;type:decimal(5,2);comment:每小时成功率" json:"success_rate_hour"`                                     // 每小时成功率
	Speed           string    `gorm:"column:speed;type:varchar(8);not null;default:16,1;comment:发件速度 xx秒 xx 封 ---> 8秒 1 封：8,1    1秒 3 封：1,3" json:"speed"`    // 发件速度 xx秒 xx 封 ---> 8秒 1 封：8,1    1秒 3 封：1,3
	CreateTime      time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime      time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName EmlDomainCredibility's table name
func (*EmlDomainCredibility) TableName() string {
	return TableNameEmlDomainCredibility
}
