// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlRedemptionCode = "eml_redemption_codes"

// EmlRedemptionCode 存储一些兑换码
type EmlRedemptionCode struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid             int64      `gorm:"column:cid;type:bigint;not null;comment:商户id" json:"cid"`                                              // 商户id
	TaskSubID       int64      `gorm:"column:task_sub_id;type:bigint;not null;comment:邮件任务 ID" json:"task_sub_id"`                           // 邮件任务 ID
	Code            string     `gorm:"column:code;type:varchar(64);not null;comment:兑换码" json:"code"`                                        // 兑换码
	Type            string     `gorm:"column:type;type:varchar(32);not null;default:credit;comment:兑换码类别（credit）" json:"type"`               // 兑换码类别（credit）
	Amount          int32      `gorm:"column:amount;type:int;not null;comment:兑换值(100)" json:"amount"`                                       // 兑换值(100)
	EndTime         *time.Time `gorm:"column:end_time;type:timestamp;comment:失效时间" json:"end_time"`                                          // 失效时间
	StartTime       *time.Time `gorm:"column:start_time;type:timestamp;comment:生效时间" json:"start_time"`                                      // 生效时间
	AmountValidTime *time.Time `gorm:"column:amount_valid_time;type:timestamp;comment:兑换后有效期" json:"amount_valid_time"`                      // 兑换后有效期
	Status          int32      `gorm:"column:status;type:int;not null;comment:是否已经使用（0：未使用，1：已使用）" json:"status"`                            // 是否已经使用（0：未使用，1：已使用）
	UID             *string    `gorm:"column:uid;type:varchar(64);comment:被哪个用户使用" json:"uid"`                                               // 被哪个用户使用
	UsedTime        *time.Time `gorm:"column:used_time;type:timestamp;comment:使用时间" json:"used_time"`                                        // 使用时间
	CreateTime      time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EmlRedemptionCode's table name
func (*EmlRedemptionCode) TableName() string {
	return TableNameEmlRedemptionCode
}
