// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlRedemptionTaskSub = "eml_redemption_task_sub"

// EmlRedemptionTaskSub 记录兑换码信息和邮件任务关系
type EmlRedemptionTaskSub struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid        int64     `gorm:"column:cid;type:bigint;not null;comment:商户ID" json:"cid"`                    // 商户ID
	TaskSubID  int64     `gorm:"column:task_sub_id;type:bigint;not null;comment:邮件任务 ID" json:"task_sub_id"` // 邮件任务 ID
	Type       string    `gorm:"column:type;type:varchar(32);not null;comment:目标兑换码类型" json:"type"`          // 目标兑换码类型
	Amount     int32     `gorm:"column:amount;type:int;not null;comment:目标兑换码的兑换值" json:"amount"`            // 目标兑换码的兑换值
	PaymentID  string    `gorm:"column:payment_id;type:varchar(64);not null;uniqueIndex:eml_redemption_task_sub_payment_id_uindex,priority:1" json:"payment_id"`
	Code       string    `gorm:"column:code;type:varchar(64);not null;comment:使用的兑换码" json:"code"` // 使用的兑换码
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName EmlRedemptionTaskSub's table name
func (*EmlRedemptionTaskSub) TableName() string {
	return TableNameEmlRedemptionTaskSub
}
