// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlTemplate = "eml_templates"

// EmlTemplate mapped from table <eml_templates>
type EmlTemplate struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid          int64     `gorm:"column:cid;type:bigint;not null;comment:关联商户 ID" json:"cid"`                                                            // 关联商户 ID
	Category     string    `gorm:"column:category;type:varchar(32);not null;default:common;comment:模板类型，目前有：普通（common）、推荐奖励（redemption）" json:"category"` // 模板类型，目前有：普通（common）、推荐奖励（redemption）
	ContentType  string    `gorm:"column:content_type;type:varchar(32);not null;comment:模板类型(text/HTML 或 text/plain)" json:"content_type"`                // 模板类型(text/HTML 或 text/plain)
	TemplateName string    `gorm:"column:template_name;type:varchar(64);not null;comment:模板名称" json:"template_name"`                                      // 模板名称
	Priority     int32     `gorm:"column:priority;type:int;not null;default:100;comment:优先级（越小越优先）" json:"priority"`                                      // 优先级（越小越优先）
	MaxRetry     int32     `gorm:"column:max_retry;type:int;not null;comment:最大重试次数" json:"max_retry"`                                                    // 最大重试次数
	SubjectZh    string    `gorm:"column:subject_zh;type:varchar(255);not null;comment:邮件中文标题" json:"subject_zh"`                                         // 邮件中文标题
	SubjectEn    string    `gorm:"column:subject_en;type:varchar(255);not null;comment:邮件英文标题" json:"subject_en"`                                         // 邮件英文标题
	FromName     string    `gorm:"column:from_name;type:varchar(64);not null;comment:发送人名称" json:"from_name"`                                             // 发送人名称
	ContentZh    *string   `gorm:"column:content_zh;type:longtext;comment:中文模板" json:"content_zh"`                                                        // 中文模板
	ContentEn    string    `gorm:"column:content_en;type:longtext;not null;comment:英文模板" json:"content_en"`                                               // 英文模板
	Description  string    `gorm:"column:description;type:varchar(512);not null;comment:模板描述（非必需）" json:"description"`                                    // 模板描述（非必需）
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                  // 更新时间
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                  // 创建时间
}

// TableName EmlTemplate's table name
func (*EmlTemplate) TableName() string {
	return TableNameEmlTemplate
}
