// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlSysUser = "eml_sys_users"

// EmlSysUser 系统级用户关于邮件的配置信息
type EmlSysUser struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid             int64     `gorm:"column:cid;type:bigint;not null;comment:商户ID，关联商户" json:"cid"`                                                         // 商户ID，关联商户
	Type            string    `gorm:"column:type;type:varchar(16);not null;default:common;comment:邮件账号用途（common营销、redemption兑换码）" json:"type"`              // 邮件账号用途（common营销、redemption兑换码）
	Host            string    `gorm:"column:host;type:varchar(64);not null;comment:smtp 服务器" json:"host"`                                                   // smtp 服务器
	EmailServer     string    `gorm:"column:email_server;type:varchar(32);not null;default:ali;comment:服务商" json:"email_server"`                            // 服务商
	Port            int32     `gorm:"column:port;type:int;not null;comment:端口" json:"port"`                                                                 // 端口
	Username        string    `gorm:"column:username;type:varchar(128);not null;comment:smtp服务用户名" json:"username"`                                         // smtp服务用户名
	DefaultSpeed    string    `gorm:"column:default_speed;type:varchar(16);not null;default:16,1;comment:默认发件速度" json:"default_speed"`                      // 默认发件速度
	Password        string    `gorm:"column:password;type:text;not null;comment:对称加密后的密码（授权码）" json:"password"`                                             // 对称加密后的密码（授权码）
	FetchStartTime  time.Time `gorm:"column:fetch_start_time;type:timestamp;not null;default:2025-05-09 00:00:00;comment:爬取任务起始时间" json:"fetch_start_time"` // 爬取任务起始时间
	AccessKeyID     string    `gorm:"column:access_key_id;type:varchar(255);not null" json:"access_key_id"`
	AccessKeySecret string    `gorm:"column:access_key_secret;type:varchar(255);not null" json:"access_key_secret"`
	FromAddress     string    `gorm:"column:from_address;type:varchar(64);not null;comment:发件人地址" json:"from_address"`                      // 发件人地址
	ReplyTo         string    `gorm:"column:reply_to;type:varchar(255);not null;comment:回信地址" json:"reply_to"`                              // 回信地址
	EventTrack      *string   `gorm:"column:event_track;type:text;comment:埋点事件变量，以 json 形式存储。存储内容为 kv 键值对数组" json:"event_track"`            // 埋点事件变量，以 json 形式存储。存储内容为 kv 键值对数组
	UpdateTime      time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	CreateTime      time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName EmlSysUser's table name
func (*EmlSysUser) TableName() string {
	return TableNameEmlSysUser
}
