// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmlUnsubscribeUsrUser = "eml_unsubscribe_usr_users"

// EmlUnsubscribeUsrUser mapped from table <eml_unsubscribe_usr_users>
type EmlUnsubscribeUsrUser struct {
	ID  int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid int64   `gorm:"column:cid;type:bigint;not null;uniqueIndex:email_unsubscribe_usr_users_cid_uid_uindex,priority:1;comment:商户ID" json:"cid"` // 商户ID
	UID *string `gorm:"column:uid;type:varchar(128);uniqueIndex:email_unsubscribe_usr_users_cid_uid_uindex,priority:2;comment:用户ID" json:"uid"`    // 用户ID
	Spm string  `gorm:"column:spm;type:varchar(128);not null" json:"spm"`
	IP  string  `gorm:"column:ip;type:varchar(39);not null" json:"ip"`
}

// TableName EmlUnsubscribeUsrUser's table name
func (*EmlUnsubscribeUsrUser) TableName() string {
	return TableNameEmlUnsubscribeUsrUser
}
