// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlTag = "eml_tags"

// EmlTag mapped from table <eml_tags>
type EmlTag struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid         int64     `gorm:"column:cid;type:bigint;not null;comment:关联商户 ID" json:"cid"`                                           // 关联商户 ID
	Tag         string    `gorm:"column:tag;type:varchar(64);not null;comment:标签" json:"tag"`                                           // 标签
	Description string    `gorm:"column:description;type:varchar(1024);not null;comment:标签描述" json:"description"`                       // 标签描述
	UpdateTime  time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	CreateTime  time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName EmlTag's table name
func (*EmlTag) TableName() string {
	return TableNameEmlTag
}
