// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlTaskConfig = "eml_task_config"

// EmlTaskConfig 任务配置表
type EmlTaskConfig struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid        int64     `gorm:"column:cid;type:bigint;not null" json:"cid"`
	Category   string    `gorm:"column:category;type:varchar(36);not null;default:email;comment:任务类型(大分类）" json:"category"` // 任务类型(大分类）
	Type       string    `gorm:"column:type;type:varchar(36);not null;default:market;comment:任务类型（小分类）" json:"type"`        // 任务类型（小分类）
	Priority   int32     `gorm:"column:priority;type:int;not null;default:100;comment:值越小，优先级越高" json:"priority"`           // 值越小，优先级越高
	MaxRetry   int32     `gorm:"column:max_retry;type:int;not null;default:3;comment:最大重试次数" json:"max_retry"`              // 最大重试次数
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName EmlTaskConfig's table name
func (*EmlTaskConfig) TableName() string {
	return TableNameEmlTaskConfig
}
