// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmlTaskSub = "eml_task_subs"

// EmlTaskSub mapped from table <eml_task_subs>
type EmlTaskSub struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid             int64      `gorm:"column:cid;type:bigint;not null;comment:关联商户 ID" json:"cid"` // 关联商户 ID
	TaskID          int64      `gorm:"column:task_id;type:bigint;not null;uniqueIndex:email_task_subs_task_id_to_user_id_uindex,priority:1" json:"task_id"`
	FromEmail       string     `gorm:"column:from_email;type:varchar(255);not null;comment:发件人地址" json:"from_email"`                                                                     // 发件人地址
	ToUserID        string     `gorm:"column:to_user_id;type:varchar(128);not null;uniqueIndex:email_task_subs_task_id_to_user_id_uindex,priority:2;comment:收件人用户 ID" json:"to_user_id"` // 收件人用户 ID
	ToEmail         string     `gorm:"column:to_email;type:varchar(255);not null;comment:收件人邮箱" json:"to_email"`                                                                         // 收件人邮箱
	TemplateID      int64      `gorm:"column:template_id;type:bigint;not null" json:"template_id"`
	Data            string     `gorm:"column:data;type:varchar(2048);not null;comment:邮件内容变量" json:"data"`                                                                                                              // 邮件内容变量
	Status          string     `gorm:"column:status;type:varchar(32);not null;index:eml_task_subs_status_retry_priority_index,priority:1;default:unsent;comment:任务状态(init、ing、fail、done、opened、clicked)" json:"status"` // 任务状态(init、ing、fail、done、opened、clicked)
	Type            string     `gorm:"column:type;type:varchar(36);not null;default:market;comment:邮件任务类型" json:"type"`                                                                                                 // 邮件任务类型
	Priority        int32      `gorm:"column:priority;type:int;not null;index:eml_task_subs_status_retry_priority_index,priority:3;default:100;comment:数值越小，优先级越高" json:"priority"`                                     // 数值越小，优先级越高
	Retry           int32      `gorm:"column:retry;type:int;not null;index:eml_task_subs_status_retry_priority_index,priority:2;comment:重试次数" json:"retry"`                                                             // 重试次数
	Version         int32      `gorm:"column:version;type:int;not null;comment:乐观锁" json:"version"`                                                                                                                     // 乐观锁
	FetchTime       time.Time  `gorm:"column:fetch_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:上次获取事件" json:"fetch_time"`                                                                            // 上次获取事件
	CodeSMTP        string     `gorm:"column:code_smtp;type:varchar(8);not null;comment:smtp 服务器返回码" json:"code_smtp"`                                                                                                  // smtp 服务器返回码
	CodeDescription string     `gorm:"column:code_description;type:varchar(2048);not null;comment:返回码描述" json:"code_description"`                                                                                       // 返回码描述
	SentTime        *time.Time `gorm:"column:sent_time;type:timestamp;comment:发件时间" json:"sent_time"`                                                                                                                   // 发件时间
	EmailDomain     string     `gorm:"column:email_domain;type:varchar(64);not null;comment:收件域" json:"email_domain"`                                                                                                   // 收件域
	UpdateTime      time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                                                                            // 更新时间
	CreateTime      time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                                                            // 创建时间
}

// TableName EmlTaskSub's table name
func (*EmlTaskSub) TableName() string {
	return TableNameEmlTaskSub
}
