// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOpsEmlNumberSuccess = "ops_eml_number_successes"

// OpsEmlNumberSuccess mapped from table <ops_eml_number_successes>
type OpsEmlNumberSuccess struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cid          int64     `gorm:"column:cid;type:bigint;not null" json:"cid"`
	FromAddress  string    `gorm:"column:from_address;type:varchar(255);not null;comment:发件人邮箱" json:"from_address"` // 发件人邮箱
	Domain       string    `gorm:"column:domain;type:varchar(255);not null;comment:收件域" json:"domain"`               // 收件域
	StartTime    time.Time `gorm:"column:start_time;type:datetime;not null;comment:区间开始时间" json:"start_time"`       // 区间开始时间
	EndTime      time.Time `gorm:"column:end_time;type:datetime;not null;comment:区间结束时间" json:"end_time"`           // 区间结束时间
	SuccessCnt   int32     `gorm:"column:success_cnt;type:int;not null;comment:成功发送数量" json:"success_cnt"`           // 成功发送数量
	TemporaryErr int32     `gorm:"column:temporary_err;type:int;not null;comment:临时错误（可重试）" json:"temporary_err"`    // 临时错误（可重试）
	PermanentErr int32     `gorm:"column:permanent_err;type:int;not null;comment:永久错误（不可重试）" json:"permanent_err"`   // 永久错误（不可重试）
	TotalCnt     int32     `gorm:"column:total_cnt;type:int;not null;comment:总发送数量" json:"total_cnt"`                // 总发送数量
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName OpsEmlNumberSuccess's table name
func (*OpsEmlNumberSuccess) TableName() string {
	return TableNameOpsEmlNumberSuccess
}
