// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsrUser = "usr_users"

// UsrUser mapped from table <usr_users>
type UsrUser struct {
	ID            int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID        string         `gorm:"column:user_id;type:varchar(128);not null;uniqueIndex:uk,priority:1;comment:商户平台的用户唯一id" json:"user_id"` // 商户平台的用户唯一id
	FullName      string         `gorm:"column:full_name;type:varchar(128);not null;comment:全名" json:"full_name"`                                // 全名
	FirstName     string         `gorm:"column:first_name;type:varchar(32);not null;comment:名字" json:"first_name"`                               // 名字
	MiddleName    *string        `gorm:"column:middle_name;type:varchar(32);comment:中间名" json:"middle_name"`                                     // 中间名
	LastName      string         `gorm:"column:last_name;type:varchar(32);not null;comment:姓氏" json:"last_name"`                                 // 姓氏
	Email         string         `gorm:"column:email;type:varchar(64);not null;comment:电子邮件" json:"email"`                                       // 电子邮件
	Language      string         `gorm:"column:language;type:varchar(16);not null;comment:用户默认语言" json:"language"`                               // 用户默认语言
	LastIP        *string        `gorm:"column:last_ip;type:varchar(45);comment:用户最近一次登录ip" json:"last_ip"`                                      // 用户最近一次登录ip
	LastHostname  *string        `gorm:"column:last_hostname;type:varchar(255);comment:用户最近一次登录的hostname" json:"last_hostname"`                  // 用户最近一次登录的hostname
	LastLoginTime *time.Time     `gorm:"column:last_login_time;type:datetime(3);comment:用户最近一次登录时间" json:"last_login_time"`                      // 用户最近一次登录时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:用户更新时间" json:"updated_at"`                           // 用户更新时间
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:用户创建时间" json:"created_at"`                           // 用户创建时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:用户删除时间" json:"deleted_at"`                                    // 用户删除时间
	Cid           int64          `gorm:"column:cid;type:bigint;not null;uniqueIndex:uk,priority:2;comment:数据所属的商户id" json:"cid"`                 // 数据所属的商户id
	GmtCreate     *time.Time     `gorm:"column:gmt_create;type:datetime(3);comment:创建时间" json:"gmt_create"`                                      // 创建时间
	GmtUpdate     *time.Time     `gorm:"column:gmt_update;type:datetime(3);comment:更新时间" json:"gmt_update"`                                      // 更新时间
	Tags          string         `gorm:"column:tags;type:varchar(1024);not null;comment:用户标签，可以有多个，存储形式["a","b","c"]" json:"tags"`               // 用户标签，可以有多个，存储形式["a","b","c"]
}

// TableName UsrUser's table name
func (*UsrUser) TableName() string {
	return TableNameUsrUser
}
