// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"email/dal/model"
)

func newEmailTag(db *gorm.DB, opts ...gen.DOOption) emailTag {
	_emailTag := emailTag{}

	_emailTag.emailTagDo.UseDB(db, opts...)
	_emailTag.emailTagDo.UseModel(&model.EmlTag{})

	tableName := _emailTag.emailTagDo.TableName()
	_emailTag.ALL = field.NewAsterisk(tableName)
	_emailTag.ID = field.NewInt64(tableName, "id")
	_emailTag.Cid = field.NewInt64(tableName, "cid")
	_emailTag.Tag = field.NewString(tableName, "tag")
	_emailTag.Description = field.NewString(tableName, "description")
	_emailTag.UpdateTime = field.NewTime(tableName, "update_time")
	_emailTag.CreateTime = field.NewTime(tableName, "create_time")

	_emailTag.fillFieldMap()

	return _emailTag
}

type emailTag struct {
	emailTagDo emailTagDo

	ALL         field.Asterisk
	ID          field.Int64
	Cid         field.Int64  // 关联商户 ID
	Tag         field.String // 标签
	Description field.String // 标签描述
	UpdateTime  field.Time   // 更新时间
	CreateTime  field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (e emailTag) Table(newTableName string) *emailTag {
	e.emailTagDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emailTag) As(alias string) *emailTag {
	e.emailTagDo.DO = *(e.emailTagDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emailTag) updateTableName(table string) *emailTag {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Cid = field.NewInt64(table, "cid")
	e.Tag = field.NewString(table, "tag")
	e.Description = field.NewString(table, "description")
	e.UpdateTime = field.NewTime(table, "update_time")
	e.CreateTime = field.NewTime(table, "create_time")

	e.fillFieldMap()

	return e
}

func (e *emailTag) WithContext(ctx context.Context) *emailTagDo { return e.emailTagDo.WithContext(ctx) }

func (e emailTag) TableName() string { return e.emailTagDo.TableName() }

func (e emailTag) Alias() string { return e.emailTagDo.Alias() }

func (e emailTag) Columns(cols ...field.Expr) gen.Columns { return e.emailTagDo.Columns(cols...) }

func (e *emailTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emailTag) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 6)
	e.fieldMap["id"] = e.ID
	e.fieldMap["cid"] = e.Cid
	e.fieldMap["tag"] = e.Tag
	e.fieldMap["description"] = e.Description
	e.fieldMap["update_time"] = e.UpdateTime
	e.fieldMap["create_time"] = e.CreateTime
}

func (e emailTag) clone(db *gorm.DB) emailTag {
	e.emailTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emailTag) replaceDB(db *gorm.DB) emailTag {
	e.emailTagDo.ReplaceDB(db)
	return e
}

type emailTagDo struct{ gen.DO }

func (e emailTagDo) Debug() *emailTagDo {
	return e.withDO(e.DO.Debug())
}

func (e emailTagDo) WithContext(ctx context.Context) *emailTagDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emailTagDo) ReadDB() *emailTagDo {
	return e.Clauses(dbresolver.Read)
}

func (e emailTagDo) WriteDB() *emailTagDo {
	return e.Clauses(dbresolver.Write)
}

func (e emailTagDo) Session(config *gorm.Session) *emailTagDo {
	return e.withDO(e.DO.Session(config))
}

func (e emailTagDo) Clauses(conds ...clause.Expression) *emailTagDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emailTagDo) Returning(value interface{}, columns ...string) *emailTagDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emailTagDo) Not(conds ...gen.Condition) *emailTagDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emailTagDo) Or(conds ...gen.Condition) *emailTagDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emailTagDo) Select(conds ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emailTagDo) Where(conds ...gen.Condition) *emailTagDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emailTagDo) Order(conds ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emailTagDo) Distinct(cols ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emailTagDo) Omit(cols ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emailTagDo) Join(table schema.Tabler, on ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emailTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emailTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emailTagDo) Group(cols ...field.Expr) *emailTagDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emailTagDo) Having(conds ...gen.Condition) *emailTagDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emailTagDo) Limit(limit int) *emailTagDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emailTagDo) Offset(offset int) *emailTagDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emailTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emailTagDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emailTagDo) Unscoped() *emailTagDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emailTagDo) Create(values ...*model.EmlTag) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emailTagDo) CreateInBatches(values []*model.EmlTag, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emailTagDo) Save(values ...*model.EmlTag) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emailTagDo) First() (*model.EmlTag, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTag), nil
	}
}

func (e emailTagDo) Take() (*model.EmlTag, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTag), nil
	}
}

func (e emailTagDo) Last() (*model.EmlTag, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTag), nil
	}
}

func (e emailTagDo) Find() ([]*model.EmlTag, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmlTag), err
}

func (e emailTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmlTag, err error) {
	buf := make([]*model.EmlTag, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emailTagDo) FindInBatches(result *[]*model.EmlTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emailTagDo) Attrs(attrs ...field.AssignExpr) *emailTagDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emailTagDo) Assign(attrs ...field.AssignExpr) *emailTagDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emailTagDo) Joins(fields ...field.RelationField) *emailTagDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emailTagDo) Preload(fields ...field.RelationField) *emailTagDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emailTagDo) FirstOrInit() (*model.EmlTag, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTag), nil
	}
}

func (e emailTagDo) FirstOrCreate() (*model.EmlTag, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTag), nil
	}
}

func (e emailTagDo) FindByPage(offset int, limit int) (result []*model.EmlTag, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emailTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emailTagDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emailTagDo) Delete(models ...*model.EmlTag) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emailTagDo) withDO(do gen.Dao) *emailTagDo {
	e.DO = *do.(*gen.DO)
	return e
}
