// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"email/dal/model"
)

func newEmlUnsubscribeUsrUser(db *gorm.DB, opts ...gen.DOOption) emlUnsubscribeUsrUser {
	_emlUnsubscribeUsrUser := emlUnsubscribeUsrUser{}

	_emlUnsubscribeUsrUser.emlUnsubscribeUsrUserDo.UseDB(db, opts...)
	_emlUnsubscribeUsrUser.emlUnsubscribeUsrUserDo.UseModel(&model.EmlUnsubscribeUsrUser{})

	tableName := _emlUnsubscribeUsrUser.emlUnsubscribeUsrUserDo.TableName()
	_emlUnsubscribeUsrUser.ALL = field.NewAsterisk(tableName)
	_emlUnsubscribeUsrUser.ID = field.NewInt64(tableName, "id")
	_emlUnsubscribeUsrUser.Cid = field.NewInt64(tableName, "cid")
	_emlUnsubscribeUsrUser.UID = field.NewString(tableName, "uid")
	_emlUnsubscribeUsrUser.Spm = field.NewString(tableName, "spm")
	_emlUnsubscribeUsrUser.IP = field.NewString(tableName, "ip")

	_emlUnsubscribeUsrUser.fillFieldMap()

	return _emlUnsubscribeUsrUser
}

type emlUnsubscribeUsrUser struct {
	emlUnsubscribeUsrUserDo emlUnsubscribeUsrUserDo

	ALL field.Asterisk
	ID  field.Int64
	Cid field.Int64  // 商户ID
	UID field.String // 用户ID
	Spm field.String
	IP  field.String

	fieldMap map[string]field.Expr
}

func (e emlUnsubscribeUsrUser) Table(newTableName string) *emlUnsubscribeUsrUser {
	e.emlUnsubscribeUsrUserDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emlUnsubscribeUsrUser) As(alias string) *emlUnsubscribeUsrUser {
	e.emlUnsubscribeUsrUserDo.DO = *(e.emlUnsubscribeUsrUserDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emlUnsubscribeUsrUser) updateTableName(table string) *emlUnsubscribeUsrUser {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Cid = field.NewInt64(table, "cid")
	e.UID = field.NewString(table, "uid")
	e.Spm = field.NewString(table, "spm")
	e.IP = field.NewString(table, "ip")

	e.fillFieldMap()

	return e
}

func (e *emlUnsubscribeUsrUser) WithContext(ctx context.Context) *emlUnsubscribeUsrUserDo {
	return e.emlUnsubscribeUsrUserDo.WithContext(ctx)
}

func (e emlUnsubscribeUsrUser) TableName() string { return e.emlUnsubscribeUsrUserDo.TableName() }

func (e emlUnsubscribeUsrUser) Alias() string { return e.emlUnsubscribeUsrUserDo.Alias() }

func (e emlUnsubscribeUsrUser) Columns(cols ...field.Expr) gen.Columns {
	return e.emlUnsubscribeUsrUserDo.Columns(cols...)
}

func (e *emlUnsubscribeUsrUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emlUnsubscribeUsrUser) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["id"] = e.ID
	e.fieldMap["cid"] = e.Cid
	e.fieldMap["uid"] = e.UID
	e.fieldMap["spm"] = e.Spm
	e.fieldMap["ip"] = e.IP
}

func (e emlUnsubscribeUsrUser) clone(db *gorm.DB) emlUnsubscribeUsrUser {
	e.emlUnsubscribeUsrUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emlUnsubscribeUsrUser) replaceDB(db *gorm.DB) emlUnsubscribeUsrUser {
	e.emlUnsubscribeUsrUserDo.ReplaceDB(db)
	return e
}

type emlUnsubscribeUsrUserDo struct{ gen.DO }

func (e emlUnsubscribeUsrUserDo) Debug() *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Debug())
}

func (e emlUnsubscribeUsrUserDo) WithContext(ctx context.Context) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emlUnsubscribeUsrUserDo) ReadDB() *emlUnsubscribeUsrUserDo {
	return e.Clauses(dbresolver.Read)
}

func (e emlUnsubscribeUsrUserDo) WriteDB() *emlUnsubscribeUsrUserDo {
	return e.Clauses(dbresolver.Write)
}

func (e emlUnsubscribeUsrUserDo) Session(config *gorm.Session) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Session(config))
}

func (e emlUnsubscribeUsrUserDo) Clauses(conds ...clause.Expression) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emlUnsubscribeUsrUserDo) Returning(value interface{}, columns ...string) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emlUnsubscribeUsrUserDo) Not(conds ...gen.Condition) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emlUnsubscribeUsrUserDo) Or(conds ...gen.Condition) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emlUnsubscribeUsrUserDo) Select(conds ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emlUnsubscribeUsrUserDo) Where(conds ...gen.Condition) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emlUnsubscribeUsrUserDo) Order(conds ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emlUnsubscribeUsrUserDo) Distinct(cols ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emlUnsubscribeUsrUserDo) Omit(cols ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emlUnsubscribeUsrUserDo) Join(table schema.Tabler, on ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emlUnsubscribeUsrUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emlUnsubscribeUsrUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emlUnsubscribeUsrUserDo) Group(cols ...field.Expr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emlUnsubscribeUsrUserDo) Having(conds ...gen.Condition) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emlUnsubscribeUsrUserDo) Limit(limit int) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emlUnsubscribeUsrUserDo) Offset(offset int) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emlUnsubscribeUsrUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emlUnsubscribeUsrUserDo) Unscoped() *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emlUnsubscribeUsrUserDo) Create(values ...*model.EmlUnsubscribeUsrUser) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emlUnsubscribeUsrUserDo) CreateInBatches(values []*model.EmlUnsubscribeUsrUser, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emlUnsubscribeUsrUserDo) Save(values ...*model.EmlUnsubscribeUsrUser) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emlUnsubscribeUsrUserDo) First() (*model.EmlUnsubscribeUsrUser, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlUnsubscribeUsrUser), nil
	}
}

func (e emlUnsubscribeUsrUserDo) Take() (*model.EmlUnsubscribeUsrUser, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlUnsubscribeUsrUser), nil
	}
}

func (e emlUnsubscribeUsrUserDo) Last() (*model.EmlUnsubscribeUsrUser, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlUnsubscribeUsrUser), nil
	}
}

func (e emlUnsubscribeUsrUserDo) Find() ([]*model.EmlUnsubscribeUsrUser, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmlUnsubscribeUsrUser), err
}

func (e emlUnsubscribeUsrUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmlUnsubscribeUsrUser, err error) {
	buf := make([]*model.EmlUnsubscribeUsrUser, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emlUnsubscribeUsrUserDo) FindInBatches(result *[]*model.EmlUnsubscribeUsrUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emlUnsubscribeUsrUserDo) Attrs(attrs ...field.AssignExpr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emlUnsubscribeUsrUserDo) Assign(attrs ...field.AssignExpr) *emlUnsubscribeUsrUserDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emlUnsubscribeUsrUserDo) Joins(fields ...field.RelationField) *emlUnsubscribeUsrUserDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emlUnsubscribeUsrUserDo) Preload(fields ...field.RelationField) *emlUnsubscribeUsrUserDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emlUnsubscribeUsrUserDo) FirstOrInit() (*model.EmlUnsubscribeUsrUser, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlUnsubscribeUsrUser), nil
	}
}

func (e emlUnsubscribeUsrUserDo) FirstOrCreate() (*model.EmlUnsubscribeUsrUser, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlUnsubscribeUsrUser), nil
	}
}

func (e emlUnsubscribeUsrUserDo) FindByPage(offset int, limit int) (result []*model.EmlUnsubscribeUsrUser, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emlUnsubscribeUsrUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emlUnsubscribeUsrUserDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emlUnsubscribeUsrUserDo) Delete(models ...*model.EmlUnsubscribeUsrUser) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emlUnsubscribeUsrUserDo) withDO(do gen.Dao) *emlUnsubscribeUsrUserDo {
	e.DO = *do.(*gen.DO)
	return e
}
