// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"email/dal/model"
)

func newEmlRedemptionCode(db *gorm.DB, opts ...gen.DOOption) emlRedemptionCode {
	_emlRedemptionCode := emlRedemptionCode{}

	_emlRedemptionCode.emlRedemptionCodeDo.UseDB(db, opts...)
	_emlRedemptionCode.emlRedemptionCodeDo.UseModel(&model.EmlRedemptionCode{})

	tableName := _emlRedemptionCode.emlRedemptionCodeDo.TableName()
	_emlRedemptionCode.ALL = field.NewAsterisk(tableName)
	_emlRedemptionCode.ID = field.NewInt64(tableName, "id")
	_emlRedemptionCode.Cid = field.NewInt64(tableName, "cid")
	_emlRedemptionCode.TaskSubID = field.NewInt64(tableName, "task_sub_id")
	_emlRedemptionCode.Code = field.NewString(tableName, "code")
	_emlRedemptionCode.Type = field.NewString(tableName, "type")
	_emlRedemptionCode.Amount = field.NewInt32(tableName, "amount")
	_emlRedemptionCode.EndTime = field.NewTime(tableName, "end_time")
	_emlRedemptionCode.StartTime = field.NewTime(tableName, "start_time")
	_emlRedemptionCode.AmountValidTime = field.NewTime(tableName, "amount_valid_time")
	_emlRedemptionCode.Status = field.NewInt32(tableName, "status")
	_emlRedemptionCode.UID = field.NewString(tableName, "uid")
	_emlRedemptionCode.UsedTime = field.NewTime(tableName, "used_time")
	_emlRedemptionCode.CreateTime = field.NewTime(tableName, "create_time")
	_emlRedemptionCode.UpdateTime = field.NewTime(tableName, "update_time")

	_emlRedemptionCode.fillFieldMap()

	return _emlRedemptionCode
}

// emlRedemptionCode 存储一些兑换码
type emlRedemptionCode struct {
	emlRedemptionCodeDo emlRedemptionCodeDo

	ALL             field.Asterisk
	ID              field.Int64
	Cid             field.Int64  // 商户id
	TaskSubID       field.Int64  // 邮件任务 ID
	Code            field.String // 兑换码
	Type            field.String // 兑换码类别（credit）
	Amount          field.Int32  // 兑换值(100)
	EndTime         field.Time   // 失效时间
	StartTime       field.Time   // 生效时间
	AmountValidTime field.Time   // 兑换后有效期
	Status          field.Int32  // 是否已经使用（0：未使用，1：已使用）
	UID             field.String // 被哪个用户使用
	UsedTime        field.Time   // 使用时间
	CreateTime      field.Time   // 创建时间
	UpdateTime      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (e emlRedemptionCode) Table(newTableName string) *emlRedemptionCode {
	e.emlRedemptionCodeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emlRedemptionCode) As(alias string) *emlRedemptionCode {
	e.emlRedemptionCodeDo.DO = *(e.emlRedemptionCodeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emlRedemptionCode) updateTableName(table string) *emlRedemptionCode {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Cid = field.NewInt64(table, "cid")
	e.TaskSubID = field.NewInt64(table, "task_sub_id")
	e.Code = field.NewString(table, "code")
	e.Type = field.NewString(table, "type")
	e.Amount = field.NewInt32(table, "amount")
	e.EndTime = field.NewTime(table, "end_time")
	e.StartTime = field.NewTime(table, "start_time")
	e.AmountValidTime = field.NewTime(table, "amount_valid_time")
	e.Status = field.NewInt32(table, "status")
	e.UID = field.NewString(table, "uid")
	e.UsedTime = field.NewTime(table, "used_time")
	e.CreateTime = field.NewTime(table, "create_time")
	e.UpdateTime = field.NewTime(table, "update_time")

	e.fillFieldMap()

	return e
}

func (e *emlRedemptionCode) WithContext(ctx context.Context) *emlRedemptionCodeDo {
	return e.emlRedemptionCodeDo.WithContext(ctx)
}

func (e emlRedemptionCode) TableName() string { return e.emlRedemptionCodeDo.TableName() }

func (e emlRedemptionCode) Alias() string { return e.emlRedemptionCodeDo.Alias() }

func (e emlRedemptionCode) Columns(cols ...field.Expr) gen.Columns {
	return e.emlRedemptionCodeDo.Columns(cols...)
}

func (e *emlRedemptionCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emlRedemptionCode) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 14)
	e.fieldMap["id"] = e.ID
	e.fieldMap["cid"] = e.Cid
	e.fieldMap["task_sub_id"] = e.TaskSubID
	e.fieldMap["code"] = e.Code
	e.fieldMap["type"] = e.Type
	e.fieldMap["amount"] = e.Amount
	e.fieldMap["end_time"] = e.EndTime
	e.fieldMap["start_time"] = e.StartTime
	e.fieldMap["amount_valid_time"] = e.AmountValidTime
	e.fieldMap["status"] = e.Status
	e.fieldMap["uid"] = e.UID
	e.fieldMap["used_time"] = e.UsedTime
	e.fieldMap["create_time"] = e.CreateTime
	e.fieldMap["update_time"] = e.UpdateTime
}

func (e emlRedemptionCode) clone(db *gorm.DB) emlRedemptionCode {
	e.emlRedemptionCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emlRedemptionCode) replaceDB(db *gorm.DB) emlRedemptionCode {
	e.emlRedemptionCodeDo.ReplaceDB(db)
	return e
}

type emlRedemptionCodeDo struct{ gen.DO }

func (e emlRedemptionCodeDo) Debug() *emlRedemptionCodeDo {
	return e.withDO(e.DO.Debug())
}

func (e emlRedemptionCodeDo) WithContext(ctx context.Context) *emlRedemptionCodeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emlRedemptionCodeDo) ReadDB() *emlRedemptionCodeDo {
	return e.Clauses(dbresolver.Read)
}

func (e emlRedemptionCodeDo) WriteDB() *emlRedemptionCodeDo {
	return e.Clauses(dbresolver.Write)
}

func (e emlRedemptionCodeDo) Session(config *gorm.Session) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Session(config))
}

func (e emlRedemptionCodeDo) Clauses(conds ...clause.Expression) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emlRedemptionCodeDo) Returning(value interface{}, columns ...string) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emlRedemptionCodeDo) Not(conds ...gen.Condition) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emlRedemptionCodeDo) Or(conds ...gen.Condition) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emlRedemptionCodeDo) Select(conds ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emlRedemptionCodeDo) Where(conds ...gen.Condition) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emlRedemptionCodeDo) Order(conds ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emlRedemptionCodeDo) Distinct(cols ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emlRedemptionCodeDo) Omit(cols ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emlRedemptionCodeDo) Join(table schema.Tabler, on ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emlRedemptionCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emlRedemptionCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emlRedemptionCodeDo) Group(cols ...field.Expr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emlRedemptionCodeDo) Having(conds ...gen.Condition) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emlRedemptionCodeDo) Limit(limit int) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emlRedemptionCodeDo) Offset(offset int) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emlRedemptionCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emlRedemptionCodeDo) Unscoped() *emlRedemptionCodeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emlRedemptionCodeDo) Create(values ...*model.EmlRedemptionCode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emlRedemptionCodeDo) CreateInBatches(values []*model.EmlRedemptionCode, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emlRedemptionCodeDo) Save(values ...*model.EmlRedemptionCode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emlRedemptionCodeDo) First() (*model.EmlRedemptionCode, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionCode), nil
	}
}

func (e emlRedemptionCodeDo) Take() (*model.EmlRedemptionCode, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionCode), nil
	}
}

func (e emlRedemptionCodeDo) Last() (*model.EmlRedemptionCode, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionCode), nil
	}
}

func (e emlRedemptionCodeDo) Find() ([]*model.EmlRedemptionCode, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmlRedemptionCode), err
}

func (e emlRedemptionCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmlRedemptionCode, err error) {
	buf := make([]*model.EmlRedemptionCode, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emlRedemptionCodeDo) FindInBatches(result *[]*model.EmlRedemptionCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emlRedemptionCodeDo) Attrs(attrs ...field.AssignExpr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emlRedemptionCodeDo) Assign(attrs ...field.AssignExpr) *emlRedemptionCodeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emlRedemptionCodeDo) Joins(fields ...field.RelationField) *emlRedemptionCodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emlRedemptionCodeDo) Preload(fields ...field.RelationField) *emlRedemptionCodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emlRedemptionCodeDo) FirstOrInit() (*model.EmlRedemptionCode, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionCode), nil
	}
}

func (e emlRedemptionCodeDo) FirstOrCreate() (*model.EmlRedemptionCode, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionCode), nil
	}
}

func (e emlRedemptionCodeDo) FindByPage(offset int, limit int) (result []*model.EmlRedemptionCode, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emlRedemptionCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emlRedemptionCodeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emlRedemptionCodeDo) Delete(models ...*model.EmlRedemptionCode) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emlRedemptionCodeDo) withDO(do gen.Dao) *emlRedemptionCodeDo {
	e.DO = *do.(*gen.DO)
	return e
}
