// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"email/dal/model"
)

func newEmlRedemptionTaskSub(db *gorm.DB, opts ...gen.DOOption) emlRedemptionTaskSub {
	_emlRedemptionTaskSub := emlRedemptionTaskSub{}

	_emlRedemptionTaskSub.emlRedemptionTaskSubDo.UseDB(db, opts...)
	_emlRedemptionTaskSub.emlRedemptionTaskSubDo.UseModel(&model.EmlRedemptionTaskSub{})

	tableName := _emlRedemptionTaskSub.emlRedemptionTaskSubDo.TableName()
	_emlRedemptionTaskSub.ALL = field.NewAsterisk(tableName)
	_emlRedemptionTaskSub.ID = field.NewInt64(tableName, "id")
	_emlRedemptionTaskSub.Cid = field.NewInt64(tableName, "cid")
	_emlRedemptionTaskSub.TaskSubID = field.NewInt64(tableName, "task_sub_id")
	_emlRedemptionTaskSub.Type = field.NewString(tableName, "type")
	_emlRedemptionTaskSub.Amount = field.NewInt32(tableName, "amount")
	_emlRedemptionTaskSub.PaymentID = field.NewString(tableName, "payment_id")
	_emlRedemptionTaskSub.Code = field.NewString(tableName, "code")
	_emlRedemptionTaskSub.CreateTime = field.NewTime(tableName, "create_time")
	_emlRedemptionTaskSub.UpdateTime = field.NewTime(tableName, "update_time")

	_emlRedemptionTaskSub.fillFieldMap()

	return _emlRedemptionTaskSub
}

// emlRedemptionTaskSub 记录兑换码信息和邮件任务关系
type emlRedemptionTaskSub struct {
	emlRedemptionTaskSubDo emlRedemptionTaskSubDo

	ALL        field.Asterisk
	ID         field.Int64
	Cid        field.Int64  // 商户ID
	TaskSubID  field.Int64  // 邮件任务 ID
	Type       field.String // 目标兑换码类型
	Amount     field.Int32  // 目标兑换码的兑换值
	PaymentID  field.String
	Code       field.String // 使用的兑换码
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (e emlRedemptionTaskSub) Table(newTableName string) *emlRedemptionTaskSub {
	e.emlRedemptionTaskSubDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emlRedemptionTaskSub) As(alias string) *emlRedemptionTaskSub {
	e.emlRedemptionTaskSubDo.DO = *(e.emlRedemptionTaskSubDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emlRedemptionTaskSub) updateTableName(table string) *emlRedemptionTaskSub {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Cid = field.NewInt64(table, "cid")
	e.TaskSubID = field.NewInt64(table, "task_sub_id")
	e.Type = field.NewString(table, "type")
	e.Amount = field.NewInt32(table, "amount")
	e.PaymentID = field.NewString(table, "payment_id")
	e.Code = field.NewString(table, "code")
	e.CreateTime = field.NewTime(table, "create_time")
	e.UpdateTime = field.NewTime(table, "update_time")

	e.fillFieldMap()

	return e
}

func (e *emlRedemptionTaskSub) WithContext(ctx context.Context) *emlRedemptionTaskSubDo {
	return e.emlRedemptionTaskSubDo.WithContext(ctx)
}

func (e emlRedemptionTaskSub) TableName() string { return e.emlRedemptionTaskSubDo.TableName() }

func (e emlRedemptionTaskSub) Alias() string { return e.emlRedemptionTaskSubDo.Alias() }

func (e emlRedemptionTaskSub) Columns(cols ...field.Expr) gen.Columns {
	return e.emlRedemptionTaskSubDo.Columns(cols...)
}

func (e *emlRedemptionTaskSub) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emlRedemptionTaskSub) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["cid"] = e.Cid
	e.fieldMap["task_sub_id"] = e.TaskSubID
	e.fieldMap["type"] = e.Type
	e.fieldMap["amount"] = e.Amount
	e.fieldMap["payment_id"] = e.PaymentID
	e.fieldMap["code"] = e.Code
	e.fieldMap["create_time"] = e.CreateTime
	e.fieldMap["update_time"] = e.UpdateTime
}

func (e emlRedemptionTaskSub) clone(db *gorm.DB) emlRedemptionTaskSub {
	e.emlRedemptionTaskSubDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emlRedemptionTaskSub) replaceDB(db *gorm.DB) emlRedemptionTaskSub {
	e.emlRedemptionTaskSubDo.ReplaceDB(db)
	return e
}

type emlRedemptionTaskSubDo struct{ gen.DO }

func (e emlRedemptionTaskSubDo) Debug() *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Debug())
}

func (e emlRedemptionTaskSubDo) WithContext(ctx context.Context) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emlRedemptionTaskSubDo) ReadDB() *emlRedemptionTaskSubDo {
	return e.Clauses(dbresolver.Read)
}

func (e emlRedemptionTaskSubDo) WriteDB() *emlRedemptionTaskSubDo {
	return e.Clauses(dbresolver.Write)
}

func (e emlRedemptionTaskSubDo) Session(config *gorm.Session) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Session(config))
}

func (e emlRedemptionTaskSubDo) Clauses(conds ...clause.Expression) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emlRedemptionTaskSubDo) Returning(value interface{}, columns ...string) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emlRedemptionTaskSubDo) Not(conds ...gen.Condition) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emlRedemptionTaskSubDo) Or(conds ...gen.Condition) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emlRedemptionTaskSubDo) Select(conds ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emlRedemptionTaskSubDo) Where(conds ...gen.Condition) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emlRedemptionTaskSubDo) Order(conds ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emlRedemptionTaskSubDo) Distinct(cols ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emlRedemptionTaskSubDo) Omit(cols ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emlRedemptionTaskSubDo) Join(table schema.Tabler, on ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emlRedemptionTaskSubDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emlRedemptionTaskSubDo) RightJoin(table schema.Tabler, on ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emlRedemptionTaskSubDo) Group(cols ...field.Expr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emlRedemptionTaskSubDo) Having(conds ...gen.Condition) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emlRedemptionTaskSubDo) Limit(limit int) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emlRedemptionTaskSubDo) Offset(offset int) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emlRedemptionTaskSubDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emlRedemptionTaskSubDo) Unscoped() *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emlRedemptionTaskSubDo) Create(values ...*model.EmlRedemptionTaskSub) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emlRedemptionTaskSubDo) CreateInBatches(values []*model.EmlRedemptionTaskSub, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emlRedemptionTaskSubDo) Save(values ...*model.EmlRedemptionTaskSub) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emlRedemptionTaskSubDo) First() (*model.EmlRedemptionTaskSub, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionTaskSub), nil
	}
}

func (e emlRedemptionTaskSubDo) Take() (*model.EmlRedemptionTaskSub, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionTaskSub), nil
	}
}

func (e emlRedemptionTaskSubDo) Last() (*model.EmlRedemptionTaskSub, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionTaskSub), nil
	}
}

func (e emlRedemptionTaskSubDo) Find() ([]*model.EmlRedemptionTaskSub, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmlRedemptionTaskSub), err
}

func (e emlRedemptionTaskSubDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmlRedemptionTaskSub, err error) {
	buf := make([]*model.EmlRedemptionTaskSub, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emlRedemptionTaskSubDo) FindInBatches(result *[]*model.EmlRedemptionTaskSub, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emlRedemptionTaskSubDo) Attrs(attrs ...field.AssignExpr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emlRedemptionTaskSubDo) Assign(attrs ...field.AssignExpr) *emlRedemptionTaskSubDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emlRedemptionTaskSubDo) Joins(fields ...field.RelationField) *emlRedemptionTaskSubDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emlRedemptionTaskSubDo) Preload(fields ...field.RelationField) *emlRedemptionTaskSubDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emlRedemptionTaskSubDo) FirstOrInit() (*model.EmlRedemptionTaskSub, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionTaskSub), nil
	}
}

func (e emlRedemptionTaskSubDo) FirstOrCreate() (*model.EmlRedemptionTaskSub, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlRedemptionTaskSub), nil
	}
}

func (e emlRedemptionTaskSubDo) FindByPage(offset int, limit int) (result []*model.EmlRedemptionTaskSub, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emlRedemptionTaskSubDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emlRedemptionTaskSubDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emlRedemptionTaskSubDo) Delete(models ...*model.EmlRedemptionTaskSub) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emlRedemptionTaskSubDo) withDO(do gen.Dao) *emlRedemptionTaskSubDo {
	e.DO = *do.(*gen.DO)
	return e
}
