// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"email/dal/model"
)

func newEmlTask(db *gorm.DB, opts ...gen.DOOption) emlTask {
	_emlTask := emlTask{}

	_emlTask.emlTaskDo.UseDB(db, opts...)
	_emlTask.emlTaskDo.UseModel(&model.EmlTask{})

	tableName := _emlTask.emlTaskDo.TableName()
	_emlTask.ALL = field.NewAsterisk(tableName)
	_emlTask.ID = field.NewInt64(tableName, "id")
	_emlTask.Cid = field.NewInt64(tableName, "cid")
	_emlTask.FromEmail = field.NewString(tableName, "from_email")
	_emlTask.UserTag = field.NewString(tableName, "user_tag")
	_emlTask.TemplateID = field.NewInt64(tableName, "template_id")
	_emlTask.Status = field.NewString(tableName, "status")
	_emlTask.Type = field.NewString(tableName, "type")
	_emlTask.ProcessInfo = field.NewString(tableName, "process_info")
	_emlTask.Version = field.NewInt32(tableName, "version")
	_emlTask.FetchTime = field.NewTime(tableName, "fetch_time")
	_emlTask.TotalNum = field.NewInt32(tableName, "total_num")
	_emlTask.SuccessNum = field.NewInt32(tableName, "success_num")
	_emlTask.FailNum = field.NewInt32(tableName, "fail_num")
	_emlTask.InvalidNum = field.NewInt32(tableName, "invalid_num")
	_emlTask.PendingNum = field.NewInt32(tableName, "pending_num")
	_emlTask.OpenNum = field.NewInt32(tableName, "open_num")
	_emlTask.OpenNumDe = field.NewInt32(tableName, "open_num_de")
	_emlTask.ClickNum = field.NewInt32(tableName, "click_num")
	_emlTask.ClickNumDe = field.NewInt32(tableName, "click_num_de")
	_emlTask.UpdateTime = field.NewTime(tableName, "update_time")
	_emlTask.CreateTime = field.NewTime(tableName, "create_time")

	_emlTask.fillFieldMap()

	return _emlTask
}

type emlTask struct {
	emlTaskDo emlTaskDo

	ALL         field.Asterisk
	ID          field.Int64
	Cid         field.Int64  // 商户ID，关联商户
	FromEmail   field.String // 发信人地址
	UserTag     field.String // 用于筛选用户
	TemplateID  field.Int64  // 模板ID
	Status      field.String // 发件任务状态（pending、processing、finished、invalid）
	Type        field.String // 发件任务类型
	ProcessInfo field.String // 发件任务处理信息
	Version     field.Int32  // 乐观锁
	FetchTime   field.Time   // 上次获取时间
	TotalNum    field.Int32  // 发件总数 等价于 收件人数量
	SuccessNum  field.Int32  // 成功发送的数量
	FailNum     field.Int32  // 邮件任务失败的数量
	InvalidNum  field.Int32  // 收件人地址有误总数
	PendingNum  field.Int32  // 等待被发送的邮件数量
	OpenNum     field.Int32  // 收到邮件后，打开邮件的行为
	OpenNumDe   field.Int32  // 对”打开”行为基于同一封邮件做去重
	ClickNum    field.Int32  // 收到邮件后，打开邮件后，点击了邮件中的URL
	ClickNumDe  field.Int32  // 对”点击”行为基于同一封邮件做去重
	UpdateTime  field.Time   // 更新时间
	CreateTime  field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (e emlTask) Table(newTableName string) *emlTask {
	e.emlTaskDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emlTask) As(alias string) *emlTask {
	e.emlTaskDo.DO = *(e.emlTaskDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emlTask) updateTableName(table string) *emlTask {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Cid = field.NewInt64(table, "cid")
	e.FromEmail = field.NewString(table, "from_email")
	e.UserTag = field.NewString(table, "user_tag")
	e.TemplateID = field.NewInt64(table, "template_id")
	e.Status = field.NewString(table, "status")
	e.Type = field.NewString(table, "type")
	e.ProcessInfo = field.NewString(table, "process_info")
	e.Version = field.NewInt32(table, "version")
	e.FetchTime = field.NewTime(table, "fetch_time")
	e.TotalNum = field.NewInt32(table, "total_num")
	e.SuccessNum = field.NewInt32(table, "success_num")
	e.FailNum = field.NewInt32(table, "fail_num")
	e.InvalidNum = field.NewInt32(table, "invalid_num")
	e.PendingNum = field.NewInt32(table, "pending_num")
	e.OpenNum = field.NewInt32(table, "open_num")
	e.OpenNumDe = field.NewInt32(table, "open_num_de")
	e.ClickNum = field.NewInt32(table, "click_num")
	e.ClickNumDe = field.NewInt32(table, "click_num_de")
	e.UpdateTime = field.NewTime(table, "update_time")
	e.CreateTime = field.NewTime(table, "create_time")

	e.fillFieldMap()

	return e
}

func (e *emlTask) WithContext(ctx context.Context) *emlTaskDo { return e.emlTaskDo.WithContext(ctx) }

func (e emlTask) TableName() string { return e.emlTaskDo.TableName() }

func (e emlTask) Alias() string { return e.emlTaskDo.Alias() }

func (e emlTask) Columns(cols ...field.Expr) gen.Columns { return e.emlTaskDo.Columns(cols...) }

func (e *emlTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emlTask) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 21)
	e.fieldMap["id"] = e.ID
	e.fieldMap["cid"] = e.Cid
	e.fieldMap["from_email"] = e.FromEmail
	e.fieldMap["user_tag"] = e.UserTag
	e.fieldMap["template_id"] = e.TemplateID
	e.fieldMap["status"] = e.Status
	e.fieldMap["type"] = e.Type
	e.fieldMap["process_info"] = e.ProcessInfo
	e.fieldMap["version"] = e.Version
	e.fieldMap["fetch_time"] = e.FetchTime
	e.fieldMap["total_num"] = e.TotalNum
	e.fieldMap["success_num"] = e.SuccessNum
	e.fieldMap["fail_num"] = e.FailNum
	e.fieldMap["invalid_num"] = e.InvalidNum
	e.fieldMap["pending_num"] = e.PendingNum
	e.fieldMap["open_num"] = e.OpenNum
	e.fieldMap["open_num_de"] = e.OpenNumDe
	e.fieldMap["click_num"] = e.ClickNum
	e.fieldMap["click_num_de"] = e.ClickNumDe
	e.fieldMap["update_time"] = e.UpdateTime
	e.fieldMap["create_time"] = e.CreateTime
}

func (e emlTask) clone(db *gorm.DB) emlTask {
	e.emlTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emlTask) replaceDB(db *gorm.DB) emlTask {
	e.emlTaskDo.ReplaceDB(db)
	return e
}

type emlTaskDo struct{ gen.DO }

func (e emlTaskDo) Debug() *emlTaskDo {
	return e.withDO(e.DO.Debug())
}

func (e emlTaskDo) WithContext(ctx context.Context) *emlTaskDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emlTaskDo) ReadDB() *emlTaskDo {
	return e.Clauses(dbresolver.Read)
}

func (e emlTaskDo) WriteDB() *emlTaskDo {
	return e.Clauses(dbresolver.Write)
}

func (e emlTaskDo) Session(config *gorm.Session) *emlTaskDo {
	return e.withDO(e.DO.Session(config))
}

func (e emlTaskDo) Clauses(conds ...clause.Expression) *emlTaskDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emlTaskDo) Returning(value interface{}, columns ...string) *emlTaskDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emlTaskDo) Not(conds ...gen.Condition) *emlTaskDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emlTaskDo) Or(conds ...gen.Condition) *emlTaskDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emlTaskDo) Select(conds ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emlTaskDo) Where(conds ...gen.Condition) *emlTaskDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emlTaskDo) Order(conds ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emlTaskDo) Distinct(cols ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emlTaskDo) Omit(cols ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emlTaskDo) Join(table schema.Tabler, on ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emlTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emlTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emlTaskDo) Group(cols ...field.Expr) *emlTaskDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emlTaskDo) Having(conds ...gen.Condition) *emlTaskDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emlTaskDo) Limit(limit int) *emlTaskDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emlTaskDo) Offset(offset int) *emlTaskDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emlTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emlTaskDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emlTaskDo) Unscoped() *emlTaskDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emlTaskDo) Create(values ...*model.EmlTask) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emlTaskDo) CreateInBatches(values []*model.EmlTask, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emlTaskDo) Save(values ...*model.EmlTask) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emlTaskDo) First() (*model.EmlTask, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTask), nil
	}
}

func (e emlTaskDo) Take() (*model.EmlTask, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTask), nil
	}
}

func (e emlTaskDo) Last() (*model.EmlTask, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTask), nil
	}
}

func (e emlTaskDo) Find() ([]*model.EmlTask, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmlTask), err
}

func (e emlTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmlTask, err error) {
	buf := make([]*model.EmlTask, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emlTaskDo) FindInBatches(result *[]*model.EmlTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emlTaskDo) Attrs(attrs ...field.AssignExpr) *emlTaskDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emlTaskDo) Assign(attrs ...field.AssignExpr) *emlTaskDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emlTaskDo) Joins(fields ...field.RelationField) *emlTaskDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emlTaskDo) Preload(fields ...field.RelationField) *emlTaskDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emlTaskDo) FirstOrInit() (*model.EmlTask, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTask), nil
	}
}

func (e emlTaskDo) FirstOrCreate() (*model.EmlTask, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmlTask), nil
	}
}

func (e emlTaskDo) FindByPage(offset int, limit int) (result []*model.EmlTask, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emlTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emlTaskDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emlTaskDo) Delete(models ...*model.EmlTask) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emlTaskDo) withDO(do gen.Dao) *emlTaskDo {
	e.DO = *do.(*gen.DO)
	return e
}
